package org.rublin.exception;

/**
 * Custom exception. Using when user try to access to not existing task
 *
 * @author Ruslan Sheremet
 * @see
 * @since 1.0
 */
public class TaskNotFoundException extends Exception {
}
